name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up npm config and authenticate
        run: |
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_REGISTRY_PACKAGES }}" > ~/.npmrc
      - name: Install dependencies and build with npm
        run: |
          npm install @allied-solutions/affinity@9.2.0
          npm run build # or any other command to build your project
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Change this to the directory where your build artifacts are located

        

            

