name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up npm config
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > $HOME/.npmrc
          echo "@allied-solutions:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
          echo "always-auth=true" >> $HOME/.npmrc

      - name: Install dependencies and build with yarn
        run: |
          yarn install --frozen-lockfile
